name: Windows – Lifemanager
on:
    workflow_dispatch:

jobs:
  build:
  name: Start Building
  runs-on: window-latest

  steps:
  - name: Downloading & installing Essentials
    run: |
      Invoke-WEBRequest Url "https://gitlab.com/chamod12/Im_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
      cmd /c Downloads.bat

  - name: Connect to Lifemanager
    run: cmd /c show.bat
  - name: Time Counter
    run: cmd /c loop.bat
